### PR TITLE
Feature/#262 style upload button

### PR DESCRIPTION
**Pull request by crowesn**
Resolves https://github.com/uclibs/scholar_uc/issues/262

### CODE REVIEW

**Comment by hortongn** [comment]
:+1: I'd like at least one other person to try this in their own environment and make sure it behaves as expected.

**Comment by jamesvanmil** [comment]
Sean - a few comments:

* The text on the button should be different. 'Add+' is used elsewhere with different functionality. Perhaps 'Select files'.
* The filename is editable after selection - make uneditable?
* Is it possible to show the file names for all files? - We'll also want to use the same interface in the page to attach files to an existing work. This currently (by design) doesn't support multiple file upload, so it'd be good if you could easily turn this on off.
* The button doesn't have any color in vanilla Curate - should probably be sharing some class with another button to pick up some color?

**Comment by crowesn** [comment]
@jamesvanmil for point 3, the current behavior is to show filename for single selected file. Won't this work (without a change) in cases where input is limited single file?

**Comment by jamesvanmil** [comment]
+1

**Comment by scherztc** [comment]
See https://github.com/uclibs/curate_fork/pull/90

**Pull request closed without merging**
