### PR TITLE
apply upload styling to all file inputs

### PR DESCRIPTION
**Pull request by crowesn**
Resolves https://github.com/uclibs/scholar_uc/issues/533

### CODE REVIEW

**Comment by hortongn** [comment]
:+1: works properly for me with works, collections, and profile images

**Comment by hortongn** [comment]
This branch is now running on Larry along with James' fix for https://github.com/uclibs/scholar_uc/issues/537.  http://larry.libraries.uc.edu:3001

**_However**_, one of the files Sean changed in the Curate gem is overridden in the app (app/views/registrations/_form_attributes.html.erb).  So the button for uploading a profile pic is still the old style.  A separate commit will need to be made for that file in the app.

**Comment by crowesn** [comment]
It looks like we're overriding in the app for shibboleth integration -
https://github.com/uclibs/scholar_uc/blob/develop/app/views/registrations/_form_attributes.html.erb

@hortongn: anything preventing this from just migrating to the curate_fork?

**Comment by hortongn** [comment]
@crowesn So we either need to update _form_attributes.html.erb in scholar_uc with your change OR remove _form_attributes.html.erb from scholar_uc and add the Shibboleth specific code to curate_uc.  

Either way, it requires a change to the scholar_uc repo.  Since your change to that file is just one line, I say we just update _form_attributes.html.erb in scholar_uc to use your new render line.  Then open a PR for that and we will merge both the curate_fork and scholar_uc PRs at the same time.

**Pull request merged**
